# Generated by Django 4.2.5 on 2023-10-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300, verbose_name='Имя')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/products', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ('-date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Suggests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300, verbose_name='Имя')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/products', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ('-date', 'title'),
            },
        ),
    ]
