# Generated by Django 4.2.5 on 2023-10-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
