# Generated by Django 4.2.5 on 2023-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
