# Generated by Django 4.2.5 on 2023-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_commentrating_alter_postcomments_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CommentRating',
        ),
    ]
